### PR TITLE
125 event scheduler

### PR DESCRIPTION
**Pull request by MarshallAsch**
Closes: #125 

**Describe the pull request:**

Can now finally schedule recurring messages to be sent. This uses cron style specifications because it is waaaaay easier than parsing english. This also sets the ground work for being able to do other kinds of scheduled messages like reminders, jobs to be run later, scheduled commands etc. 

---

Checklist:

- [x] Run `npm run lint` and ensure linter passes
- [x] Run `npm run test` and ensure tests pass
- [x] Verify that the changes work as expected on Discord
- [x] Update documentation / not applicable
- [x] Update changelog / not applicable

### CODE REVIEW

**Review by SoorajModi — APPROVED** [review]
Lgtm, cool feature

**Comment by MarshallAsch** [comment]
@SoorajModi I think this is ready for a re-review

**Review by SoorajModi — APPROVED** [review]

**Comment by SoorajModi** [comment]
Fixes are good

**Comment by MarshallAsch** [comment]
Im not sure what you think but currently the CRON scheduler will run on whatever timezone the server is using, (which should be UTC time), but that will be a bit annoying to have to convert to UTC when writing the expressions. I propose adding server timezone support based on the weather location (or possible as a separate command) so that scheduled events happen using their timezone. 

Do you think this should be added as part of this PR or a separate one?

**Comment by MarshallAsch** [comment]
@SoorajModi after adding a timezone command I think this is now ready to merge,

**Pull request merged**
