### PR TITLE
Revert "bumped dependancy versions"

### PR DESCRIPTION
**Pull request by MarshallAsch**
Reverts Botomir/Botomir#222

### CODE REVIEW

**Comment by MarshallAsch** [comment]
@SoorajModi

**Comment by MarshallAsch** [comment]
it seems like it has just started working again, I have no idea why, it seems like this is not needed

**Comment by SoorajModi** [comment]
Im gonna hold off on this, and only approve it if it keeps crashing

**Comment by MarshallAsch** [comment]
it seems like this is not needed

**Pull request closed without merging**
