### PR TITLE
207 audit channel

### PR DESCRIPTION
**Pull request by MarshallAsch**
Closes: #207 
~~Blocked by: #212~~
---

**Describe the pull request:**

Can now send all message updates and deletions to an audit channel. 
This also fixed some other issues that were present in the delete and update handlers. 

Note this is ready for review, it just may not behave as expected until the fix for #212 is merged. 

---

Checklist:

- [x] Run `npm run lint` and ensure linter passes
- [x] Run `npm run test` and ensure tests pass
- [x] Verify that the changes work as expected on Discord
- [x] Update documentation / not applicable
- [x] Update changelog / not applicable

### CODE REVIEW

**Comment by MarshallAsch** [comment]
@SoorajModi this is now ready

**Review by SoorajModi — APPROVED** [review]
Looks good!

**Comment by MarshallAsch** [comment]
@rithik-c will this implementation meet you needs? the audit messages would look something like this

image

**Comment by rithik-c** [comment]
Do we believe a time/date timestamp is necessary? other than that everything looks great!

**Comment by MarshallAsch** [comment]
> Do we believe a time/date timestamp is necessary? 

I didnt think about including a timestamp, but that would be an easy addition. The message would be sent at the same time that the message was changed / updated, so the audit message would have a timestamp, but Ill add a timestamp to the acual message as well

**Comment by MarshallAsch** [comment]
@rithik-c Im going to leave the image / video / file auditing for a separate task because we currently do not have any method to handle tracking and storing message attachments. 

Im going to merge this once the set of merge checks passes.

**Pull request merged**
